descriptor_extension: yml
package:
  description: SONATA vCDN GENERIC PLACEMENT
  maintainer: Felipe Vicens, ATOS, felipe.vicens@atos.net
  name: "son-vcdn-genericplacement"
  vendor: "eu.sonata-nfv"
  version: "0.1"
version: '0.5'
